USE [master]
GO

/****** Object:  Database [hamwic]    Script Date: 10/04/2012 23:24:47 ******/
CREATE DATABASE [hamwic] ON  PRIMARY 
( NAME = N'hamwic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.DB\MSSQL\DATA\hamwic.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'hamwic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.DB\MSSQL\DATA\hamwic_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [hamwic] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hamwic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hamwic] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hamwic] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hamwic] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hamwic] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hamwic] SET ARITHABORT OFF 
GO

ALTER DATABASE [hamwic] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hamwic] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [hamwic] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hamwic] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hamwic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hamwic] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hamwic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hamwic] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hamwic] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hamwic] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hamwic] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hamwic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hamwic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hamwic] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hamwic] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hamwic] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hamwic] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hamwic] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hamwic] SET  READ_WRITE 
GO

ALTER DATABASE [hamwic] SET RECOVERY FULL 
GO

ALTER DATABASE [hamwic] SET  MULTI_USER 
GO

ALTER DATABASE [hamwic] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hamwic] SET DB_CHAINING OFF 
GO


